name: 'friday'
description: 'cheatsheet bot'
inputs:
  CHEATSHEET_HOST:
    description: 'cheatsheet host'
    required: false
  SLACK_CHANNEL:
    description: 'slack channel name'
    required: false
  debug:
    description: 'debug flag'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
